[package]

name = "graphics"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "leonkunert <info@leonkunert.de>",
    "gmorenz",
    "Potpourri",
    "TyOverby <ty@pre-alpha.com>"]

[lib]

name = "graphics"
path = "./src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/PistonDevelopers/vecmath"

[dependencies.texture]

git = "https://github.com/PistonDevelopers/texture"

[dependencies.read_color]

git = "https://github.com/PistonDevelopers/read_color"

