[package]

name = "piston2d-graphics"
version = "0.0.7"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "leonkunert <info@leonkunert.de>",
    "gmorenz",
    "Potpourri",
    "TyOverby <ty@pre-alpha.com>"]
keywords = ["graphics", "2d", "game", "piston", "triangulation"]
description = "A library for 2D graphics that works with multiple back-ends"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/graphics.git"
homepage = "https://github.com/pistondevelopers/graphics"

[lib]

name = "graphics"
path = "./src/lib.rs"

[dependencies.vecmath]
git = "https://github.com/PistonDevelopers/vecmath"
#version = "0.0.2"

[dependencies.piston-texture]
git = "https://github.com/PistonDevelopers/texture"
#version = "0.0.1"

[dependencies.read_color]
git = "https://github.com/PistonDevelopers/read_color"
#version = "0.0.2"

[dependencies.quack]
git = "https://github.com/PistonDevelopers/quack"
#version = "0.0.2"

[dependencies.interpolation]
git = "https://github.com/PistonDevelopers/interpolation"
#version = "0.0.1"

